name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    defaults:
      run:
      # Mobile folder working directory.
        working-directory: ./Mobile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
        # we have already installed all dependencies above
         install: true
        # Cypress tests and config file are in "e2e" folder
         working-directory: mob
